title: "Đỗ Như Phong - CV"
email: donhuphong1902@gmail.com
description: >-
  Software Engineer | Đam mê công nghệ, học hỏi liên tục và phát triển phần mềm chất lượng.
baseurl: "/dnp-cv"
url: "https://donhuphong.github.io"
theme: minima

# Social
linkedin_username: donhuphong
